language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - cp .env.travis .env
  - mysql -e "create database IF NOT EXISTS homestead;" -uroot;
  - composer self-update
  - composer install --no-interaction --prefer-dist
  - php artisan migrate:install --env=testing --no-interaction -vvv
  - php artisan key:generate

script:
 - php artisan migrate --env=testing --no-interaction -vvv
 - php artisan db:seed --env=testing --no-interaction -vvv
 - php artisan migrate:rollback --env=testing --no-interaction -vvv

services:
  - mysql

notifications:
  email:
      recipients:
        - jhmread@dundee.ac.uk
      on_success: never
      on_failure: always
