language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer install --no-interaction --prefer-dist

notifications:
  email:
      recipients:
        - jhmread@dundee.ac.uk
      on_success: never
      on_failure: always
