language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  - DB=mysql

before_script:
  - cp .env.travis .env
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

  - composer self-update
  - composer install --no-interaction --prefer-dist
  - php artisan key:generate
  - php artisan migrate

 services:
  - mysql

notifications:
  email:
      recipients:
        - jhmread@dundee.ac.uk
      on_success: never
      on_failure: always
