language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction --prefer-dist
  - php artisan key:generate
  - php artisan migrate
  
before_install:
  - mysql -e 'CREATE DATABASE travis;'
 
 services:
  - mysql

notifications:
  email:
      recipients:
        - jhmread@dundee.ac.uk
      on_success: never
      on_failure: always
