language: php
dist: trusty

php:
  - 7.0
  - 7.1

before_script:
  - composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit

notifications:
  email:
      recipients:
        - contact@anthonygrimes.co.uk
      on_success: never
      on_failure: always